/* Upcoming events.
   `date` is a plain YYYY-MM-DD string — parsed as local time in the components,
   never through `new Date(string)`, which reads it as UTC and lands on the
   previous day for anyone west of Greenwich. */
export const EVENTS = [
  {
    id: "community-iftar",
    kind: "Community meal",
    spots: 60,
    address: "Iwan Hall, 14 Main Street",
    title: "Monthly Community Dinner",
    date: "2026-08-21",
    start: "18:30",
    end: "21:00",
    venue: "Iwan Hall, Main Street",
    tag: "Community",
    summary: "Food, conversation and a short reminder — everyone welcome.",
    details:
      "Our monthly sit-down for the whole community. Doors open at 6:30pm, food is served at 7, and we close with a short reminder and tea. Children are welcome and there is a supervised play corner. Come alone or bring the family — most people arrive not knowing anyone and leave with a table full of friends.",
    agenda: [
      ["18:30", "Doors open, tea and settling in"],
      ["19:00", "Food served, open tables"],
      ["20:15", "Short reminder"],
      ["20:40", "Tea, sweets and clearing up together"],
    ],
  },
  {
    id: "womens-circle",
    kind: "Study circle",
    spots: 25,
    address: "Iwan Community Room, 14 Main Street",
    title: "Iwan Women: Autumn Circle",
    date: "2026-08-29",
    start: "11:00",
    end: "13:00",
    venue: "Iwan Community Room",
    tag: "Iwan Women",
    summary: "A relaxed morning circle — study, discussion and a proper cup of tea.",
    details:
      "A monthly circle for women of every age. We read together for the first hour, then open the floor for discussion over tea and cake. No prior study is expected and there is no obligation to speak. Babies and toddlers are welcome in the room.",
    agenda: [
      ["11:00", "Arrival and tea"],
      ["11:15", "Reading together"],
      ["12:10", "Open discussion"],
      ["12:45", "Cake, and plans for next month"],
    ],
  },
  {
    id: "youth-leadership",
    kind: "Weekend programme",
    spots: 30,
    address: "Riverside Activity Centre, Mill Lane",
    title: "Iwan Youth: Leadership Weekend",
    date: "2026-09-12",
    start: "09:30",
    end: "17:00",
    venue: "Riverside Activity Centre",
    tag: "Iwan Youth",
    summary: "Two days of workshops, outdoor challenges and planning the year ahead.",
    details:
      "Our flagship weekend for 13–18s. Saturday is workshops — public speaking, project planning and running an event from scratch. Sunday moves outdoors for team challenges, then the group sets the youth programme for the coming year. Places are limited and transport can be arranged.",
    agenda: [
      ["09:30", "Arrival and team split"],
      ["10:00", "Workshop: speaking with confidence"],
      ["13:00", "Lunch"],
      ["14:00", "Outdoor challenges"],
      ["16:00", "Planning the year ahead"],
    ],
  },
  {
    id: "kids-club",
    kind: "Family morning",
    spots: 40,
    address: "Iwan Community Room, 14 Main Street",
    title: "Iwan Kids: Storytelling Morning",
    date: "2026-09-20",
    start: "10:00",
    end: "12:00",
    venue: "Iwan Community Room",
    tag: "Iwan Kids",
    summary: "Stories, crafts and games for under-10s, with parents welcome to stay.",
    details:
      "A gentle Saturday morning for our youngest members. We open with a story, move on to a craft table, and finish with games in the hall. Parents are welcome to stay for coffee at the back of the room. Suitable for ages 4–10.",
    agenda: [
      ["10:00", "Story corner"],
      ["10:40", "Craft tables"],
      ["11:20", "Games in the hall"],
      ["11:50", "Tidy-up and pick-up"],
    ],
  },
  {
    id: "mens-service-day",
    kind: "Volunteering",
    spots: 35,
    address: "Meet at Iwan Hall, 14 Main Street",
    title: "Iwan Men: Community Service Day",
    date: "2026-10-03",
    start: "08:00",
    end: "14:00",
    venue: "Meet at Iwan Hall",
    tag: "Iwan Men",
    summary: "A morning of practical work across the neighbourhood — all hands welcome.",
    details:
      "We split into small teams and take on jobs around the neighbourhood: garden clearing for elderly neighbours, painting at the community centre, and a litter sweep along the river path. Tools, gloves and lunch are provided. No skills needed — just turn up.",
    agenda: [
      ["08:00", "Breakfast and team briefing"],
      ["08:45", "Teams head out"],
      ["12:30", "Lunch back at the hall"],
      ["13:15", "Second shift for whoever can stay"],
    ],
  },
  {
    id: "open-evening",
    kind: "Open house",
    spots: 80,
    address: "Iwan Hall, 14 Main Street",
    title: "New Members Open Evening",
    date: "2026-10-17",
    start: "19:00",
    end: "20:30",
    venue: "Iwan Hall, Main Street",
    tag: "Community",
    summary: "New to the area? Come and meet the people behind every programme.",
    details:
      "An informal evening for anyone who has recently joined the community or is simply curious. Each programme lead gives a short introduction, then it is open floor over refreshments. Bring your questions — this is the easiest way to find where you fit.",
    agenda: [
      ["19:00", "Doors open, refreshments"],
      ["19:20", "Programme leads introduce themselves"],
      ["19:50", "Open floor and questions"],
      ["20:20", "Sign-ups and goodbyes"],
    ],
  },
];
